// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemoteWork.Desktop.Persistence.Data;

#nullable disable

namespace RemoteWork.Desktop.Persistence.Data.Migrations
{
    [DbContext(typeof(RemoteWorkDbContext))]
    [Migration("20261002134024_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("RemoteWork.Desktop.Persistence.Entities.ActivityBatchEntity", b =>
                {
                    b.Property<string>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ActiveDurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("EndedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSuspiciousMouseActivity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IdleDurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyboardCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MouseCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("BatchId");

                    b.HasIndex("DeviceId", "StartedAt");

                    b.HasIndex("SessionId", "StartedAt");

                    b.ToTable("ActivityBatches");
                });

            modelBuilder.Entity("RemoteWork.Desktop.Persistence.Entities.ApplicationActivityEntity", b =>
                {
                    b.Property<string>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WindowTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityId");

                    b.HasIndex("SessionId");

                    b.HasIndex("DeviceId", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("ApplicationActivities");
                });

            modelBuilder.Entity("RemoteWork.Desktop.Persistence.Entities.DeviceEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OsVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RegisteredAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeviceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("RemoteWork.Desktop.Persistence.Entities.SessionEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DeviceId", "StartedAt");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("RemoteWork.Desktop.Persistence.Entities.SyncQueueItemEntity", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SentAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("SyncQueue");
                });

            modelBuilder.Entity("RemoteWork.Desktop.Persistence.Entities.ActivityBatchEntity", b =>
                {
                    b.HasOne("RemoteWork.Desktop.Persistence.Entities.DeviceEntity", "Device")
                        .WithMany("ActivityBatches")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RemoteWork.Desktop.Persistence.Entities.SessionEntity", "Session")
                        .WithMany("ActivityBatches")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RemoteWork.Desktop.Persistence.Entities.ApplicationActivityEntity", b =>
                {
                    b.HasOne("RemoteWork.Desktop.Persistence.Entities.DeviceEntity", "Device")
                        .WithMany("ApplicationActivities")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RemoteWork.Desktop.Persistence.Entities.SessionEntity", "Session")
                        .WithMany("ApplicationActivities")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RemoteWork.Desktop.Persistence.Entities.SessionEntity", b =>
                {
                    b.HasOne("RemoteWork.Desktop.Persistence.Entities.DeviceEntity", "Device")
                        .WithMany("Sessions")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("RemoteWork.Desktop.Persistence.Entities.DeviceEntity", b =>
                {
                    b.Navigation("ActivityBatches");

                    b.Navigation("ApplicationActivities");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("RemoteWork.Desktop.Persistence.Entities.SessionEntity", b =>
                {
                    b.Navigation("ActivityBatches");

                    b.Navigation("ApplicationActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
